/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.supermarket.view;

import java.awt.Component;
import org.supermarket.model.Usuarios;

/**
 *
 * @author victorm
 */
public class VistaAdministradorHome extends javax.swing.JFrame {

    private static VistaAdministradorHome vistaAdministradorHome = null;
    private VistaInicioSesion vistaInicioSesion;
    private Usuarios usuario;

    /**
     * Creates new form VistaEmpleadoHome
     */
    VistaAdministradorHome() {
        this.setLocationRelativeTo(null);
        this.setTitle("Inicio");
        initComponents();
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnUsuario = new javax.swing.JToggleButton();
        btnProductos = new javax.swing.JToggleButton();
        btnVentas = new javax.swing.JToggleButton();
        btnCerrar_Sesion = new javax.swing.JToggleButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setRollover(true);

        btnUsuario.setBackground(new java.awt.Color(153, 153, 153));
        btnUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/supermarket/images/users-team_icon-icons.com_57998.png"))); // NOI18N
        btnUsuario.setText("Usuarios");
        btnUsuario.setFocusable(false);
        btnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioActionPerformed(evt);
            }
        });
        jToolBar1.add(btnUsuario);

        btnProductos.setBackground(new java.awt.Color(153, 153, 153));
        btnProductos.setForeground(new java.awt.Color(255, 255, 255));
        btnProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/supermarket/images/coffee-milk-bottles_icon-icons.com_61169.png"))); // NOI18N
        btnProductos.setText("Productos");
        btnProductos.setFocusable(false);
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });
        jToolBar1.add(btnProductos);

        btnVentas.setBackground(new java.awt.Color(153, 153, 153));
        btnVentas.setForeground(new java.awt.Color(255, 255, 255));
        btnVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/supermarket/images/up_high_sales_business_finance_icon-icons.com_76287.png"))); // NOI18N
        btnVentas.setText("Ventas");
        btnVentas.setFocusable(false);
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });
        jToolBar1.add(btnVentas);

        btnCerrar_Sesion.setBackground(new java.awt.Color(153, 153, 153));
        btnCerrar_Sesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar_Sesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/supermarket/images/log-out_icon-icons.com_50106.png"))); // NOI18N
        btnCerrar_Sesion.setText("Cerrar Sesión");
        btnCerrar_Sesion.setFocusable(false);
        btnCerrar_Sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrar_SesionActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCerrar_Sesion);

        jPanel1.add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 40));

        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/supermarket/images/cashier_icon-icons.com_53629.png"))); // NOI18N
        jDesktopPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 270, 260));

        jPanel1.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1200, 570));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrar_SesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrar_SesionActionPerformed
        // TODO add your handling code here:
        vistaInicioSesion = VistaInicioSesion.getInstance();
        vistaInicioSesion.setVisible(true);
        vistaAdministradorHome.setVisible(false);
    }//GEN-LAST:event_btnCerrar_SesionActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        // TODO add your handling code here:
        try {
            VistaAdministradorProductos productosAdministrador = VistaAdministradorProductos.getInstance();
            productosAdministrador.setVisible(true);

            for (Component com : jDesktopPane1.getComponents()) {
                if (com.equals(productosAdministrador)) {
                    return;
                }
            }
            jDesktopPane1.add(productosAdministrador);
        } catch (Exception e) {
        }


    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioActionPerformed
        // TODO add your handling code here:
        try {
            VistaAdministradorUsuarios vistaUsuarios = VistaAdministradorUsuarios.getInstance();
            vistaUsuarios.setVisible(true);

            for (Component com : jDesktopPane1.getComponents()) {
                if (com.equals(vistaUsuarios)) {
                    return;
                }
            }
            jDesktopPane1.add(vistaUsuarios);

        } catch (Exception e) {
        }

    }//GEN-LAST:event_btnUsuarioActionPerformed

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        // TODO add your handling code here:
        try {
            VistaAdministradorVentas vistaVentas = VistaAdministradorVentas.getInstance();
            vistaVentas.setVisible(true);

            for (Component com : jDesktopPane1.getComponents()) {
                if (com.equals(vistaVentas)) {
                    return;
                }
            }
            jDesktopPane1.add(vistaVentas);

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnVentasActionPerformed

    public static VistaAdministradorHome getInstance() {
        if (vistaAdministradorHome == null) {
            return vistaAdministradorHome = new VistaAdministradorHome();
        }
        return vistaAdministradorHome;
    }

    public void UsuarioResgistrado(Usuarios usuario) {
        this.usuario = usuario;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaAdministradorHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaAdministradorHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaAdministradorHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaAdministradorHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaAdministradorHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCerrar_Sesion;
    private javax.swing.JToggleButton btnProductos;
    private javax.swing.JToggleButton btnUsuario;
    private javax.swing.JToggleButton btnVentas;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
