/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.supermarket.view;

import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.supermarket.controller.DAOVentas;
import org.supermarket.model.Productos;
import org.supermarket.model.Ventas;

/**
 *
 * @author victorm
 */
public class VistaAdministradorVentas extends javax.swing.JInternalFrame {

    private static VistaAdministradorVentas vistaAdministradorVentas = null;
    private DAOVentas daoVentas;
    private Ventas ventas;
    private DefaultTableModel modeloTabla;
    private final java.lang.reflect.Type type = new TypeToken<List<Productos>>() {
    }.getType();
    private JComboBox comboBox;

    /**
     * Creates new form VistaAdministradorVentas
     */
    private VistaAdministradorVentas() {
        initComponents();
        daoVentas = new DAOVentas();
        modeloTabla = (DefaultTableModel) tablaVentas.getModel();
    }

    public static VistaAdministradorVentas getInstance() {
        if (vistaAdministradorVentas == null) {
            return vistaAdministradorVentas = new VistaAdministradorVentas();
        }
        return vistaAdministradorVentas;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnEliminar = new javax.swing.JToggleButton();
        btnBuscar = new javax.swing.JToggleButton();
        btnMostrarTodo = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVentas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setRollover(true);

        btnEliminar.setBackground(new java.awt.Color(153, 153, 153));
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/supermarket/images/recycle_recyclebin_full_delete_trash_1772.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setFocusable(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEliminar);

        btnBuscar.setBackground(new java.awt.Color(153, 153, 153));
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/supermarket/images/1486505375-files-folder-search-magnifying-glass-file-search-magnifier-storage_81440.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setFocusable(false);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnBuscar);

        btnMostrarTodo.setBackground(new java.awt.Color(153, 153, 153));
        btnMostrarTodo.setForeground(new java.awt.Color(255, 255, 255));
        btnMostrarTodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/supermarket/images/search_book_open_search_locate_6178.png"))); // NOI18N
        btnMostrarTodo.setText("Consultar Todo");
        btnMostrarTodo.setFocusable(false);
        btnMostrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTodoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnMostrarTodo);

        jPanel1.add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 40));

        tablaVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Fecha", "ID Empleado", "Hora", "Lista", "Total"
            }
        ));
        jScrollPane1.setViewportView(tablaVentas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 560, 210));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HIstorial de Ventas");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/supermarket/images/4882066.jpg"))); // NOI18N
        fondo.setText("jLabel2");
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 560, 310));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        long res = Long.parseLong(JOptionPane.showInputDialog(null, "Ingrese el Id"));
        ventas = new Ventas();
        ventas.setId(res);

        if (daoVentas.borrar(ventas)) {
            JOptionPane.showMessageDialog(null, "Se Elimino Correctamente");
        } else {
            JOptionPane.showMessageDialog(null, "Ocurrio Un Problema");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        modeloTabla.setRowCount(0);
        long res = Long.parseLong(JOptionPane.showInputDialog(null, "Ingrese El Id Del Producto"));
        ventas = new Ventas();
        ventas.setId(res);

        Ventas vet = daoVentas.mostrarUno(ventas);
        if (vet == null) {
            JOptionPane.showMessageDialog(null, "El Registro No Existe");
        } else {
            modeloTabla.addRow(new Object[]{
                vet.getId(),
                vet.getFecha(),
                vet.getId_empleado(),
                vet.getHora(),
                vet.getTotal()
            });
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnMostrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTodoActionPerformed
        // TODO add your handling code here:
        modeloTabla.setRowCount(0);
        List<Ventas> Lista = daoVentas.mostrarTodos();
        if (Lista.size() == 0) {
            JOptionPane.showMessageDialog(null, "No Existen Registros Aun");
        } else {
            Lista.forEach((venta) -> {
                Gson jsonArray = new Gson();
                List<Productos> lista = jsonArray.fromJson(venta.getLista(), type);
                comboBox = new JComboBox();
                for (Productos productos : lista) {
                    comboBox.addItem(productos.getNombre_producto());
                }
                tablaVentas.getColumnModel().getColumn(4).setCellEditor(new DefaultCellEditor(comboBox));
                modeloTabla.addRow(new Object[]{
                    venta.getId(),
                    venta.getFecha(),
                    venta.getId_empleado(),
                    venta.getHora(),
                    "",
                    venta.getTotal()
                });
            });
        }
    }//GEN-LAST:event_btnMostrarTodoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnBuscar;
    private javax.swing.JToggleButton btnEliminar;
    private javax.swing.JToggleButton btnMostrarTodo;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tablaVentas;
    // End of variables declaration//GEN-END:variables
}
