/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.supermarket.view;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.supermarket.controller.DAOAlmacen;
import org.supermarket.model.Productos;

/**
 *
 * @author victorm
 */
public class VistaAdministradorProductos extends javax.swing.JInternalFrame {
    private static VistaAdministradorProductos vistaAdministradorProductos = null;
    private Productos productos;
    private DAOAlmacen daoAlmacen ;
    private DefaultTableModel modeloTabla;
    /**
     * Creates new form VistaAdministradorProductos
     */
    private VistaAdministradorProductos() {
        initComponents();
        daoAlmacen = new DAOAlmacen();
        modeloTabla = (DefaultTableModel) tablaProductos.getModel();
    }
    public static VistaAdministradorProductos getInstance() {
        if (vistaAdministradorProductos == null) {
            return vistaAdministradorProductos = new VistaAdministradorProductos();
        }
        return vistaAdministradorProductos;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnNewProducto = new javax.swing.JToggleButton();
        btnActualizar = new javax.swing.JToggleButton();
        btenEliminar = new javax.swing.JToggleButton();
        btnBuscar = new javax.swing.JToggleButton();
        btnMostarTodo = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtId_producto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        txtPiezasDisponibles = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setRollover(true);

        btnNewProducto.setBackground(new java.awt.Color(153, 153, 153));
        btnNewProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnNewProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/supermarket/images/file-add_114479.png"))); // NOI18N
        btnNewProducto.setText("Crear Producto");
        btnNewProducto.setFocusable(false);
        btnNewProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewProductoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNewProducto);

        btnActualizar.setBackground(new java.awt.Color(153, 153, 153));
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/supermarket/images/Save-as_37111.png"))); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.setFocusable(false);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnActualizar);

        btenEliminar.setBackground(new java.awt.Color(153, 153, 153));
        btenEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btenEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/supermarket/images/recycle_recyclebin_full_delete_trash_1772.png"))); // NOI18N
        btenEliminar.setText("Eliminar");
        btenEliminar.setFocusable(false);
        btenEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btenEliminarActionPerformed(evt);
            }
        });
        jToolBar1.add(btenEliminar);

        btnBuscar.setBackground(new java.awt.Color(153, 153, 153));
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/supermarket/images/1486505375-files-folder-search-magnifying-glass-file-search-magnifier-storage_81440.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setFocusable(false);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnBuscar);

        btnMostarTodo.setBackground(new java.awt.Color(153, 153, 153));
        btnMostarTodo.setForeground(new java.awt.Color(255, 255, 255));
        btnMostarTodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/supermarket/images/search_book_open_search_locate_6178.png"))); // NOI18N
        btnMostarTodo.setText("Consultar Todo");
        btnMostarTodo.setFocusable(false);
        btnMostarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostarTodoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnMostarTodo);

        jPanel1.add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 50));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre : ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Descripción: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));
        jPanel1.add(txtId_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 100, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Id producto");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Precio: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Piezas Disponibles: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 100, -1));
        jPanel1.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 100, -1));
        jPanel1.add(txtPiezasDisponibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 100, -1));
        jPanel1.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 100, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Productos");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ingrese la cantidad actual que posee");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, -1));

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Descripción ", "Piezas Disponibles", "Precio"
            }
        ));
        jScrollPane1.setViewportView(tablaProductos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 660, 140));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/supermarket/images/4882066.jpg"))); // NOI18N
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 660, 360));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewProductoActionPerformed
        // TODO add your handling code here:
        productos = new Productos(Long.parseLong(txtId_producto.getText().trim()),txtNombre.getText().trim(),txtDescripcion.getText().trim(),Long.parseLong(txtPiezasDisponibles.getText().trim()),Long.parseLong(txtPrecio.getText().trim()));
        daoAlmacen.guardar(productos);
        
        
    }//GEN-LAST:event_btnNewProductoActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        productos = new Productos(Long.parseLong(txtId_producto.getText().trim()),txtNombre.getText().trim(),txtDescripcion.getText().trim(),Long.parseLong(txtPiezasDisponibles.getText().trim()),Long.parseLong(txtPrecio.getText().trim()));
        daoAlmacen.actualizar(productos);
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btenEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btenEliminarActionPerformed
        // TODO add your handling code here:
        long res = Long.parseLong(JOptionPane.showInputDialog(null , "Ingrese el id del producto"));
        productos = new Productos();
        productos.setIdProducto(res);
                
        daoAlmacen.borrar(productos);
    }//GEN-LAST:event_btenEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        modeloTabla.setRowCount(0);
        long res = Long.parseLong(JOptionPane.showInputDialog(null , "Ingrese el id del producto"));
        productos = new Productos();
        productos.setIdProducto(res);
                
        Productos prod = daoAlmacen.mostrarUno(productos);
        modeloTabla.addRow(new Object[]
            {
                prod.getIdProducto(),
                prod.getNombre_producto(),
                prod.getDescripcion(),
                prod.getPrecio(),
                prod.getPiezas()
            });
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnMostarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostarTodoActionPerformed
        // TODO add your handling code here:
        modeloTabla.setRowCount(0);
        List<Productos> Lista = daoAlmacen.mostrarTodos();

        Lista.forEach((productos) -> {
            modeloTabla.addRow(new Object[]
            {
                productos.getIdProducto(),
                productos.getNombre_producto(),
                productos.getDescripcion(),
                productos.getPrecio(),
                productos.getPiezas()
            });
        });
    }//GEN-LAST:event_btnMostarTodoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btenEliminar;
    private javax.swing.JToggleButton btnActualizar;
    private javax.swing.JToggleButton btnBuscar;
    private javax.swing.JToggleButton btnMostarTodo;
    private javax.swing.JToggleButton btnNewProducto;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtId_producto;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPiezasDisponibles;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
